var fs = require('fs');
var fp = 'C:/Users/31173/Documents/Codex/2026-05-29/https-api-luckylillia-com/jadebot/www/index.html';
var h = fs.readFileSync(fp, 'utf8');
console.log('Read:', h.length);

// 1. Add missing CSS for conn-mode cards and settings
var styleEnd = h.indexOf('</style>');
var css = '\n.conn-mode-list{display:flex;flex-direction:column;gap:12px}\n.conn-mode-card{background:var(--card);border:1px solid var(--border-light);border-radius:var(--radius);overflow:hidden;transition:all .2s}\n.conn-mode-card.active{border-color:var(--primary);box-shadow:0 0 0 1px var(--primary)}\n.conn-mode-header{display:flex;align-items:center;justify-content:space-between;padding:16px 20px}\n.conn-mode-info{display:flex;align-items:center;gap:14px}\n.conn-mode-icon{width:40px;height:40px;border-radius:10px;display:flex;align-items:center;justify-content:center;flex-shrink:0}\n.conn-mode-title{font-size:14px;font-weight:600;color:var(--text)}\n.conn-mode-desc{font-size:12px;color:var(--text3);margin-top:2px}\n.conn-mode-body{padding:0 20px 16px;border-top:1px solid var(--border-light)}\n.conn-mode-fields{display:flex;gap:16px;padding-top:14px;flex-wrap:wrap}\n.conn-field{flex:1;min-width:180px}\n.conn-field label{display:block;font-size:12px;color:var(--text3);margin-bottom:4px;font-weight:500}\n.conn-field .form-input{width:100%;padding:8px 12px;border:1px solid var(--border);border-radius:6px;font-size:13px;outline:none;transition:border .2s;font-family:var(--font)}\n.conn-field .form-input:focus{border-color:var(--primary);box-shadow:0 0 0 2px rgba(76,141,255,.1)}\n.settings-hint{font-size:12px;color:var(--text4);padding:10px 0;display:flex;align-items:center;gap:6px}\n.settings-section{background:var(--card);border-radius:var(--radius);box-shadow:var(--shadow);border:1px solid var(--border-light);padding:20px;margin-bottom:16px}\n.settings-section h3{font-size:15px;font-weight:600;color:var(--text);margin-bottom:16px;padding-bottom:12px;border-bottom:1px solid var(--border-light)}\n.form-row{display:flex;align-items:center;justify-content:space-between;padding:8px 0}\n.form-label{font-size:13px;color:var(--text2)}\n.form-input{padding:8px 12px;border:1px solid var(--border);border-radius:6px;font-size:13px;outline:none;width:220px;transition:border .2s;font-family:var(--font)}\n.form-input:focus{border-color:var(--primary);box-shadow:0 0 0 2px rgba(76,141,255,.1)}\n.toggle{position:relative;display:inline-block;width:44px;height:24px}\n.toggle input{opacity:0;width:0;height:0}\n.slider{position:absolute;cursor:pointer;top:0;left:0;right:0;bottom:0;background:var(--border);border-radius:12px;transition:.3s}\n.slider::before{position:absolute;content:" \;height:18px;width:18px;left:3px;bottom:3px;background:#fff;border-radius:50%;transition:.3s}\n.toggle input:checked+.slider{background:var(--primary)}\n.toggle input:checked+.slider::before{transform:translateX(20px)}\n.settings-actions{display:flex;gap:10px;margin-top:16px}\n.about-text{font-size:13px;color:var(--text3)}\n';
if (!h.includes('.conn-mode-card{')) {
 h = h.substring(0, styleEnd) + css + h.substring(styleEnd);
 console.log('CSS added');
}
